---
title: "IRT Simulated Data"
author: "Cassie Malcom"
date: "1/31/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)

pacman::p_load(devtools, irtoys, coda, mirt, ggmirt, tidyverse,eRm)
```

```{r}
# install.packages("devtools")
# devtools::install_github("philchalmers/mirt")
```

Simulated Dichotomous Data
```{r}
# item discrimination (needs to be fixed to 1 for Rasch model), item difficulty, and number of items
set.seed(5878)
iSim1 <- cbind(runif(20,1,1), runif(20,0,1), rep(0,20))
head(iSim1)
```

```{r}
set.seed(5878)
iSim2 <- irtoys::sim(ip=iSim1, x=rnorm(30))
head(iSim2)
```

```{r}
# write.matrix(iSim2,file="irtSIM.csv")
```


```{r}
# simD <- read.csv("/Users/cassiemalcom/Desktop/CM2020/23_Winter Term Classes/EDLD 640 DS Cap/MalcomIRTshiny/Data/irtSIM.csv", sep = " ")
```

IRT Analysis

```{r}
#rename columns for plotting
colnames(iSim2) <- c("Item 1","Item 2","Item 3","Item 4","Item 5","Item 6","Item 7","Item 8", "Item 9", "Item 10", "Item 11", "Item 12", "Item 13", "Item 14", "Item 15", "Item 16", "Item 17", "Item 18", "Item 19", "Item 20")

head(iSim2)
```


```{r}
unimodel <- mirt.model("latent = 1-20")

RaMod <- mirt::mirt(data = iSim2,
               model = unimodel,  # alternatively, we could also just specify model = 1 in this case
               itemtype = "Rasch",
               SE = TRUE) # Verbose = False stops from printing the iterations
RaMod
```

```{r}
summary(RaMod)
```

```{r}
# paramsRa <- coef(RaMod, IRTpars = TRUE, simplify = TRUE, nfact = 1)
# round(paramsRa$items, 2) # g = c = guessing parameter
```


The "a" parameter is the value of the slope, set to 1 for Rasch model.
The "b" parameter is the item location, which is its difficulty.
The "g" parameter is the lower asymptote or guessing parameter.
The "u" parameter is the upper asymptote.

Will not be showcasing g or u in this initial tutorial for Rasch.

```{r}
coef.rasch <- coef(RaMod, IRTpars=TRUE, simplify=TRUE)

items.rasch <- as.data.frame(coef.rasch$items)

IR2 <- items.rasch %>% select(-c(g, u))

colnames(IR2)[1] <- "Item Discrimination Parameter"
colnames(IR2)[2] <- "Item Location Parameter"

print(IR2)
```

```{r}
# IRT parameters from the estimated model. For this example, we are obtaining simplified output without # SEs/CIs (simplify = TRUE) for conventional IRT parameters (IRTpar = TRUE).
# coef(RaMod,simplify = TRUE, IRTpar = TRUE)$items
```

```{r}
M2(RaMod)
```

```{r}
plot(RaMod, type = "trace", theta_lim = c(-4,4), par.settings = list(superpose.line = list(col = "aquamarine1")), main="ICCs for All Items")
```

```{r}
mirt::itemplot(RaMod, 1, type = "trace", shiny = FALSE, 
               par.settings = list(superpose.line = list(col = "aquamarine1")), 
               main="Item Characteristic Curve for Item 1"
               )
```





